ARG L4T_TAG
ARG PACK_TAG
FROM nvcr.io/nvidia/l4t-base:${L4T_TAG}

ENV HOME /root

RUN apt-get -y update
RUN apt install -y libfuse-dev

# Copy appimage and binary
ADD ../bin /usr/bin

# TODO: automatically fill file name with ARG
CMD ["/usr/bin/viam-csi-0.0.1-aarch64.AppImage"]
