ARG L4T_TAG

FROM nvcr.io/nvidia/l4t-base:${L4T_TAG}

ENV HOME /root

RUN apt-get -y update
RUN apt install -y libfuse-dev

# Copy appimage and binary
ADD ../bin /usr/bin

# Run the appimage for 10 seconds and check that it exits with timeout
CMD ["/bin/sh", "-c", "timeout 10 $PACK_FILE; \
                       status=$?; \
                       if [ $status -eq 124 ]; then \
                         echo 'Command timed out'; \
                       else \
                         exit $status; \
                       fi"]
