#!/bin/bash

if [ `whoami` != "root" ]
then
   echo "Need root to install viam-csi as a system service. Try running with sudo."
   exit 1
fi

mv "$APPIMAGE" "/usr/local/bin/viam-csi"
chown root:root "/usr/local/bin/viam-csi"
chmod 755 "/usr/local/bin/viam-csi"
echo "Renamed $APPIMAGE to /usr/local/bin/viam-csi"
